### ISSUE TITLE
Question on MaraX MCU pinout

### ISSUE THREAD

**Issue by bancbanus** [larszi/marax-pressure-mod#1]
Hello Lars,

I'm really impressed by your work and I will follow your project with interest :-) 

I would appreciate if you could add more detailed information on hardware/wiring. 

In particular I'm interested in the pinout of MaraX' MCU. Today I did some measurements with a mulitmeter, but the only thing that I can confirm is that pin 4 is TX and pin 6 is VCC (around 4.4 Volts) (pin 1 is the nearest to the case edge).

In your schematics I've seen that you have a connection to the GND pin, so can you please tell me which pin is it?

Best regards!
Daniel

**Comment by larszi** [comment]
Hi Daniel,

frist of all, thank you for all the kind words about the project!
I will hopefully have time to update the Readme with a much more detailed guide in the coming days. 
The Machine I used for the Mod is the Mara X PL62X(V1, still with the Red Logo). 

Here the Pinout of the GiCar 6Pin is Vcc, Gnd, RX, TX, RTS, CT.
 
Best regards!
Lars

**Comment by ShuzzDE** [comment]
Hi Lars!
Thank you for confirming the pinout of the connector, I've been searching far and wide for it... ^^
Can you please answer my last question: Is the Vcc pin located towards the center or the edge of the control box?

Thanks a lot and kind regards!

**Comment by larszi** [comment]
The direction of the Pinout I have mentioned above is Center to Edge. Maybe I should have added that in the first place. 
I will close this Issue as I think the question regarding the pin layout has been answered, otherwise feel free to open it again :)

**Comment by hanzsez** [comment]
and do we know what the VCC voltage from the MCU is ? There are either several references online that it might be either 5V or 12V. Would like to know it without tearing and opening the machine up, if the 5V might be used to power up the esp directly utilizing the 5V input pin.
